### PR TITLE
Mappend to <>

### PR DESCRIPTION
**Pull request by chaughawout**
#35 
Swapped to operator to get rid of warnings

### CODE REVIEW

**Comment by phadej** [comment]
This will break with old GHCs.

**Comment by chaughawout** [comment]
Gotchya, I'll dig into this soon and try again. Wasn't aware of the build targets prior to the changes :)

**Comment by chaughawout** [comment]
Hey @phadej, why is this closed? Is the issue going to be closed as well?

**Comment by phadej** [comment]
I commented on the issue. This is not the approach which would work. Just disabling the warning is more pragmatic for `strict`.

**Comment by chaughawout** [comment]
Sounds good to me

**Pull request closed without merging**
